spring.config.import=optional:file:.env[.properties]
port=${PORT}
server.port=${SERVER_PORT}
server.servlet.context-path=${SERVER_SERVLET_CONTEXT_PATH}
spring.data.mongodb.ssl.enabled=${SPRING_DATA_MONGODB_SSL_ENABLED}
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE}
